---
- hosts: 127.0.0.1 
  connection: local
  gather_facts: no
  no_log: True
  tasks:
   - name: Creating directory for mounting HPSUM ISO 
     command: mkdir /mnt/HPSUM
     ignore_errors: True

   - name: Setting up loopback device
     command: losetup -r /dev/loop1 {{ HPSUM_ISO_path }} 
     ignore_errors: True

   - name: Mounting HPSUM ISO as loopback device
     command: mount /dev/loop1 /mnt/HPSUM
     ignore_errors: True
   
   - name: Cleaning any open HPSUM instances
     command: /mnt/HPSUM/hp/swpackages/hpsum shutdownengine
     ignore_errors: True

   - name: Adding HPSUM baseline
     command : /mnt/HPSUM/hp/swpackages/hpsum --open_firewall add --baselines {{ baseline_path }}
     ignore_errors: True

   - name: Inventory baseline
     command : /mnt/HPSUM/hp/swpackages/hpsum inventory --baselines {{ baseline_path }} 
     ignore_errors: True
 
   - name: Adding node to HPSUM
     command: /mnt/HPSUM/hp/swpackages/hpsum --open_firewall add --nodes {{ item }} user={{ user }} password={{ password }} type=Linux
     with_items: groups["host_list_for_FW_upgrade"]
     ignore_errors: True
 
   - name: Waiting for HPSUM to release lock
     local_action: wait_for  timeout=60

   - name: Performing HOST inventory 
     command: /mnt/HPSUM/hp/swpackages/hpsum --open_firewall inventory --nodes {{ item }} --baselines /mnt/HPSUM/hp/swpackages
     with_items: groups["host_list_for_FW_upgrade"]
     ignore_errors: True

   - name: Waiting for HPSUM to release lock
     local_action: wait_for  timeout=60

   - name: Cleaning any open HPSUM instances
     command: /mnt/HPSUM/hp/swpackages/hpsum shutdownengine 
     ignore_errors: True

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  no_log: True
  roles:
   - reporting

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  no_log: True
  roles:
   - deploy 
