---
- name: Cleaning any open HPSUM instances
  command: /mnt/HPSUM/hp/swpackages/hpsum shutdownengine
  ignore_errors: True

- name: Waiting for HPSUM to release lock
  local_action: wait_for  timeout=60
  ignore_errors: True
 
- name: Performing node reporting 
  command: /mnt/HPSUM/hp/swpackages/hpsum --open_firewall -s report -target {{ item }} -targettype Linux -veryv -username {{ user }} -password {{ password }}
  with_items: groups['host_list_for_FW_upgrade']
  ignore_errors: yes

- name: Waiting for HPSUM to release lock
  local_action: wait_for  timeout=60
  ignore_errors: True

- name: Cleaning any open HPSUM instances
  command: /mnt/HPSUM/hp/swpackages/hpsum shutdownengine 
  ignore_errors: True

- name: Waiting for HPSUM to release lock
  local_action: wait_for  timeout=60
  ignore_errors: True

- name: Generating reports for installed Firmwares
  shell: /mnt/HPSUM/hp/swpackages/hpsum --open_firewall -s -firmware_report -target {{ item }} -targettype Linux -veryv  -username {{ user }} -password {{ password }} ;sleep 60
  with_items: groups['host_list_for_FW_upgrade']
  ignore_errors: yes

- name: Waiting for HPSUM to release lock
  local_action: wait_for  timeout=60
  ignore_errors: True

- name: Cleaning any open HPSUM instances
  command: /mnt/HPSUM/hp/swpackages/hpsum shutdownengine
  ignore_errors: True
